# Generated by Django 4.1.4 on 2023-01-23 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("content", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("programming", "programming"),
                            ("tutorial", "tutorial"),
                        ],
                        default="tutorial",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "draft"), (1, "published")], default=0
                    ),
                ),
                ("date_published", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_updated",),
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=254)),
                ("content", models.TextField()),
                ("date_published", models.DateTimeField(auto_now_add=True)),
                (
                    "comment_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "ordering": ("-date_published",),
            },
        ),
    ]
