# Generated by Django 4.1.4 on 2023-02-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="", upload_to=""),
            preserve_default=False,
        ),
    ]
